package com.apppulse.sdk.internal.db

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room entity representing an analytics event in the local queue.
 *
 * This is the persistence layer representation — mapped to/from the domain
 * model [AnalyticsEvent] by the repository layer.
 *
 * The [status] column is indexed for fast queries on pending/failed events.
 *
 * Complex fields (properties, deviceInfo) are stored as JSON strings
 * rather than using Room TypeConverters, keeping the schema simple.
 */
@Entity(
    tableName = "analytics_events",
    indices = [Index(value = ["status"])]
)
internal data class AnalyticsEventEntity(
    /** UUID primary key — generated by the SDK, not auto-incremented. */
    @PrimaryKey
    val id: String,

    /** Event name (e.g., "purchase"). */
    val eventName: String,

    /** User ID at the time the event was tracked, or null. */
    val userId: String?,

    /** Event properties serialized as a JSON string, or null. */
    val propertiesJson: String?,

    /** Epoch milliseconds when the event was created. */
    val timestamp: Long,

    /** SDK version string. */
    val sdkVersion: String,

    /** Host app version, or null. */
    val appVersion: String?,

    /** Device metadata serialized as a JSON string, or null. */
    val deviceInfoJson: String?,

    /** Number of failed delivery attempts. */
    val retryCount: Int = 0,

    /** Current status: PENDING, SENDING, or FAILED. */
    val status: String = "PENDING"
)
